In [6]:
import numpy as np
print(np.__version__)
# 1.20.1

1.26.4


In [7]:
#1d array
import numpy as np

In [8]:
a1=np.array([1,2,3,4])
print(a1)

[1 2 3 4]


In [9]:
type(a1)

numpy.ndarray

In [11]:
a1.shape

(4,)

In [12]:
a1.size

4

In [14]:
#2d array
a2=np.array([[1,2,3,4],[5,6,7,8]])
print(a2)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
type(a2)

numpy.ndarray

In [16]:
a2.shape

(2, 4)

In [17]:
a2.size

8

In [18]:
a2.ndim

2

In [24]:
#3d array
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [25]:
type(a3)

numpy.ndarray

In [26]:
a3.shape

(1, 3, 3)

In [27]:
a3.size

9

In [28]:
a3.ndim

3

In [33]:
#zeros
import numpy as np
z1=np.zeros(3)
z1

array([0., 0., 0.])

In [32]:
#changing data type
z1=np.zeros(3,dtype=int)
z1

array([0, 0, 0])

In [34]:
z1.shape


(3,)

In [35]:
z1.size

3

In [36]:
z1.ndim

1

In [37]:
type(z1)

numpy.ndarray

In [38]:
z2=np.zeros((3,4))
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
z2=np.zeros((3,4),dtype=int)
z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [40]:
type(z2)

numpy.ndarray

In [41]:
z2.shape

(3, 4)

In [42]:
z2.size

12

In [43]:
z2.ndim

2

In [45]:
z3=np.zeros((2,3,4))
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [47]:
z3=np.zeros((2,3,4),dtype=int)
z3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [48]:
type(z3)

numpy.ndarray

In [49]:
z3.shape

(2, 3, 4)

In [50]:
z3.size

24

In [51]:
z3.ndim

3

In [53]:
#1d ones array
import numpy as np
a1=np.ones(3)
a1

array([1., 1., 1.])

In [54]:
a1=np.ones(3,dtype=int)
a1

array([1, 1, 1])

In [55]:
type(a1)

numpy.ndarray

In [56]:
a1.shape

(3,)

In [57]:
a1.size

3

In [58]:
a1.ndim

1

In [59]:
#2d ones array
import numpy as np
a2=np.ones((3,4))
a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
a2=np.ones((3,4),dtype=int)
a2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [61]:
type(a2)

numpy.ndarray

In [62]:
a2.shape

(3, 4)

In [63]:
a2.size

12

In [65]:
a2.ndim

2

In [74]:
#3d ones array
import numpy as np
a3=np.ones((2,3,4))
a3

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [75]:
type(a3)

numpy.ndarray

In [76]:
a3.shape

(2, 3, 4)

In [77]:
a3.size

24

In [78]:
a3.ndim

3

In [79]:
#1d full array
import numpy as np
f1=np.full(3,9)
f1

array([9, 9, 9])

In [80]:
f1=np.full(3,9,dtype=int)
f1

array([9, 9, 9])

In [81]:
type(f1)

numpy.ndarray

In [82]:
f1.shape

(3,)

In [83]:
f1.size

3

In [84]:
f1.ndim

1

In [85]:
#2d full array
import numpy as np
f2=np.full((3,4),9)
f2

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [86]:
type(f2)

numpy.ndarray

In [87]:
f2.shape

(3, 4)

In [88]:
f2.size

12

In [89]:
f2.ndim

2

In [91]:
#3d full array
import numpy as np
f3=np.full((4,2,3),10)
f3

array([[[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]]])

In [92]:
type(f3)

numpy.ndarray

In [93]:
f3.shape

(4, 2, 3)

In [94]:
f3.size

24

In [95]:
f3.ndim

3

In [96]:
a=np.array([1,2,3])
b=np.array([1,2,3])
add=np.add(a,b)
add

array([2, 4, 6])

In [97]:
a=np.array([5,10,20])
b=np.array([4,8,10])
sub=np.subtract (a,b)
sub

array([ 1,  2, 10])

In [98]:
a=np.array([5,10,20])
b=np.array([4,8,10])
mul=np.multiply (a,b)
mul

array([ 20,  80, 200])

In [99]:
a=np.array([5,10,20])
b=np.array([4,8,10])
div=np.divide (a,b)
div

array([1.25, 1.25, 2.  ])

In [100]:
a=np.array([5,10,20])
b=np.array([4,8,10])
mod=np.mod (a,b)
mod


array([1, 2, 0])

In [104]:
a=np.array([5,10,20])
b=np.array([4,8,10])
power=np.power
power

<ufunc 'power'>